//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoUniversidade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno_Turma
    {
        public int IdAluno_Turma { get; set; }
        public int IdTurma { get; set; }
        public int IdAluno { get; set; }
        public decimal media { get; set; }
        public int faltas { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
