//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoUniversidade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoTurno
    {
        public int IdCursoTurno { get; set; }
        public int IdCurso { get; set; }
        public int IdTurno { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
